using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ControleFinanceiro.Infrastructure.Migrations;

/// <summary>Plano de Ação (objetivo + etapas na linha do tempo) por usuário. SQL idempotente.</summary>
[DbContext(typeof(Persistence.AppDbContext))]
[Migration("20260720000000_AddPlanoAcao")]
public partial class AddPlanoAcao : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "PlanosAcao" (
                "Id" uuid NOT NULL,
                "UsuarioId" uuid NOT NULL,
                "Objetivo" character varying(300) NOT NULL,
                "Prazo" character varying(60),
                "CriadoEm" timestamp with time zone NOT NULL,
                "AtualizadoEm" timestamp with time zone,
                CONSTRAINT "PK_PlanosAcao" PRIMARY KEY ("Id")
            );
            """);
        migrationBuilder.Sql("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlanosAcao_UsuarioId"
                ON "PlanosAcao" ("UsuarioId");
            """);
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "EtapasPlano" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "PlanoAcaoId" uuid NOT NULL,
                "Ordem" integer NOT NULL,
                "Titulo" character varying(200) NOT NULL,
                "Descricao" character varying(1000),
                "Prazo" character varying(60),
                "Alvo" character varying(120),
                "Status" integer NOT NULL,
                CONSTRAINT "PK_EtapasPlano" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_EtapasPlano_PlanosAcao_PlanoAcaoId" FOREIGN KEY ("PlanoAcaoId")
                    REFERENCES "PlanosAcao" ("Id") ON DELETE CASCADE
            );
            """);
        migrationBuilder.Sql("""
            CREATE INDEX IF NOT EXISTS "IX_EtapasPlano_PlanoAcaoId"
                ON "EtapasPlano" ("PlanoAcaoId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"EtapasPlano\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"PlanosAcao\";");
    }
}
