using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ControleFinanceiro.Infrastructure.Migrations;

/// <summary>
/// Subtipos de investimento (2º nível por tipo), com seed básico "sistema" por tipo.
/// SQL idempotente; a sequence é reposicionada acima dos ids semeados para não colidir com custom.
/// Ids de tipo: 1=Ações 2=FII 3=ETF 4=Renda Fixa 5=Multimercado 6=Cripto 7=Exterior.
/// </summary>
[DbContext(typeof(Persistence.AppDbContext))]
[Migration("20260725500000_AddSubtiposInvestimento")]
public partial class AddSubtiposInvestimento : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "SubtiposInvestimentoParam" (
                "Id"                 integer GENERATED BY DEFAULT AS IDENTITY,
                "TipoInvestimentoId" integer NOT NULL,
                "Nome"               character varying(80) NOT NULL,
                "Ordem"              integer NOT NULL,
                "Ativo"              boolean NOT NULL,
                "IsSystem"           boolean NOT NULL,
                CONSTRAINT "PK_SubtiposInvestimentoParam" PRIMARY KEY ("Id")
            );
            """);
        migrationBuilder.Sql("""
            CREATE INDEX IF NOT EXISTS "IX_SubtiposInvestimentoParam_TipoInvestimentoId"
                ON "SubtiposInvestimentoParam" ("TipoInvestimentoId");
            """);

        // Seed "sistema" por tipo (ids fixos → ON CONFLICT DO NOTHING deixa idempotente).
        migrationBuilder.Sql("""
            INSERT INTO "SubtiposInvestimentoParam" ("Id","TipoInvestimentoId","Nome","Ordem","Ativo","IsSystem") VALUES
             (1,1,'Dividendos',1,true,true),(2,1,'Small Caps',2,true,true),(3,1,'Growth',3,true,true),(4,1,'Value',4,true,true),(5,1,'BDR',5,true,true),
             (10,2,'Tijolo',1,true,true),(11,2,'Papel',2,true,true),(12,2,'Fundo de Fundos',3,true,true),(13,2,'Híbrido',4,true,true),
             (20,3,'Índice BR',1,true,true),(21,3,'Índice Global',2,true,true),(22,3,'Setorial',3,true,true),(23,3,'Renda Fixa',4,true,true),
             (30,4,'IPCA+',1,true,true),(31,4,'Prefixado',2,true,true),(32,4,'Pós/CDI',3,true,true),(33,4,'CDB',4,true,true),(34,4,'LCI/LCA',5,true,true),(35,4,'Debênture',6,true,true),
             (40,5,'Macro',1,true,true),(41,5,'Long & Short',2,true,true),(42,5,'Quantitativo',3,true,true),(43,5,'Livre',4,true,true),
             (50,6,'Bitcoin',1,true,true),(51,6,'Ethereum',2,true,true),(52,6,'Altcoins',3,true,true),(53,6,'Stablecoin',4,true,true),
             (60,7,'Ações EUA',1,true,true),(61,7,'ETF Global',2,true,true),(62,7,'Bonds',3,true,true),(63,7,'REITs',4,true,true)
            ON CONFLICT ("Id") DO NOTHING;
            """);

        // Coloca a sequence acima dos ids semeados (custom começam em 1000+).
        migrationBuilder.Sql("""
            SELECT setval(pg_get_serial_sequence('"SubtiposInvestimentoParam"', 'Id'), 1000, true);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("""DROP TABLE IF EXISTS "SubtiposInvestimentoParam";""");
}
