// <auto-generated />
using System;
using Login.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Login.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Login.Domain.Entities.AcceptedTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TermName");

                    b.ToTable("AcceptedTerms", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.CargoAgentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Associated")
                        .HasColumnType("bit");

                    b.Property<int>("CargoAgentClientCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CargoAgentCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnassociatedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CargoAgentClients", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.CargoAgentPermission", b =>
                {
                    b.Property<Guid>("CargoAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bl")
                        .HasColumnType("bit");

                    b.Property<bool>("Booking")
                        .HasColumnType("bit");

                    b.Property<bool>("Documents")
                        .HasColumnType("bit");

                    b.Property<bool>("Tracking")
                        .HasColumnType("bit");

                    b.HasKey("CargoAgentId");

                    b.ToTable("CargoAgentPermissions", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.FreightForwarder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("FreightForwarders", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.FreightForwarderPermission", b =>
                {
                    b.Property<Guid>("FreightForwarderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bl")
                        .HasColumnType("bit");

                    b.Property<bool>("Booking")
                        .HasColumnType("bit");

                    b.Property<bool>("Documents")
                        .HasColumnType("bit");

                    b.Property<bool>("Tracking")
                        .HasColumnType("bit");

                    b.HasKey("FreightForwarderId");

                    b.ToTable("FreightForwarderPermissions", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.Hierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hierarchies", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.HierarchyCompany", b =>
                {
                    b.Property<Guid>("HierarchyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("HierarchyId", "ClientId");

                    b.ToTable("HierarchyCompanies", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HiddenMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.ModuleFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleFunctions");
                });

            modelBuilder.Entity("Login.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfileId", "ModuleId", "FunctionId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cellphone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FreightForwarderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HierarchyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Document");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.UserRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ModuleId", "CompanyId");

                    b.ToTable("UserRestrictions", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.CargoAgentPermission", b =>
                {
                    b.HasOne("Login.Domain.Entities.CargoAgentClient", null)
                        .WithOne("Permissions")
                        .HasForeignKey("Login.Domain.Entities.CargoAgentPermission", "CargoAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.FreightForwarderPermission", b =>
                {
                    b.HasOne("Login.Domain.Entities.FreightForwarder", null)
                        .WithOne("Permissions")
                        .HasForeignKey("Login.Domain.Entities.FreightForwarderPermission", "FreightForwarderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.HierarchyCompany", b =>
                {
                    b.HasOne("Login.Domain.Entities.Hierarchy", null)
                        .WithMany("Companies")
                        .HasForeignKey("HierarchyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.ModuleFunction", b =>
                {
                    b.HasOne("Login.Domain.Entities.Module", null)
                        .WithMany("Functions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.Permission", b =>
                {
                    b.HasOne("Login.Domain.Entities.Profile", null)
                        .WithMany("Permissions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.User", b =>
                {
                    b.HasOne("Login.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Login.Domain.Entities.UserRestriction", b =>
                {
                    b.HasOne("Login.Domain.Entities.User", null)
                        .WithMany("Restrictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Login.Domain.Entities.CargoAgentClient", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Login.Domain.Entities.FreightForwarder", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Login.Domain.Entities.Hierarchy", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Login.Domain.Entities.Module", b =>
                {
                    b.Navigation("Functions");
                });

            modelBuilder.Entity("Login.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Login.Domain.Entities.User", b =>
                {
                    b.Navigation("Restrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
